Repository puppetlabs/iac, pull requests merged in 2020-11, with the labels that each got.

#138 (MAINT) Write 2020-11-13 Status Update
  _posts/2020-11-13-status-update.md
Labels: blog

#141 (MAINT) Blog Update for Week 12
  _lifeofinternatpuppet/post_12.md
Labels: blog

#140 (MAINT) Write 2020-11-20 Status Update
  _posts/2020-11-20-status-update.md
Labels: blog

#142 (maint) - 2020-11-20-status-update.md doc fix
  _posts/2020-11-20-status-update.md
Labels: documentation

#143 (maint) - 2020-11-20-status-update.md life_of_intern update
  _posts/2020-11-20-status-update.md
Labels: documentation

#144 (maint) Correct link to Dishas github
  _posts/2020-11-20-status-update.md
Labels: maintenance

#145 New post: "Puppetize Digital 2020 - Content Selection"
  _lifeofinternatpuppet/post_10.md
  _lifeofinternatpuppet/post_12.md
  _lifeofinternatpuppet/post_7_and_8.md
  _posts/2020-11-23-puppetize-digital.md
Labels: blog

#147 integrate ciaran's fixes for Puppetize Digital post
  _posts/2020-11-23-puppetize-digital.md
Labels: blog, bug

#148 (blog) Status update 2020-11-27
  _posts/2020-11-27-status-update.md
Labels: blog
