Repository puppetlabs/iac, pull requests merged in 2020-10, with the labels that each got.

#119 Week 5 Blog Post
  _lifeofinternatpuppet/post_5.md
Labels: blog

#120 Status update for 2020-10-02
  _posts/2020-10-02-status-update.md
Labels: blog

#122 New post: Collecting GCP info and system metrics for Honeycomb
  _posts/2020-10-05-honeycomb-gcp-metrics.md
  assets/2020-10-05-honeycomb-gcp-metrics/first_results.png
  assets/2020-10-05-honeycomb-gcp-metrics/gcp_attributes.png
Labels: blog

#121 Remote Runner script for Litmus acceptance tests
  bin/remote_acceptance_test_runner/Gemfile
  bin/remote_acceptance_test_runner/README.md
  bin/remote_acceptance_test_runner/remote_runner.rb
Labels: enhancement

#126 2020-10-16 status update
  .gitignore
  _posts/2020-10-16-status-update.md
  bin/blog_tools/lib/common.rb
  bin/blog_tools/lib/community_prs.rb
  bin/blog_tools/lib/modules_released.rb
Labels: blog

#127 Add puppetlabs-testing module
  _modules/puppetlabs-testing.md
Labels: maintenance

#128 (maint) Update _posts/2020-10-23-status-update.md
  _posts/2020-10-23-status-update.md
Labels: blog

#129 Fix puppet_version default value
  bin/remote_acceptance_test_runner/remote_runner.rb
Labels: bug

#134 Status update for 2020-10-30 and minor enhancements
  Gemfile
  Gemfile.lock
  _config.yml
  _posts/2020-10-30-status-update.md
  bin/blog_tools/blog_template/status-update-template.md.erb
Labels: blog, enhancement
