Repository puppetlabs/iac, pull requests merged in 2020-09, with the labels that each got.

#110 Status update for 2020-09-11
  _posts/2020-09-11-status-update.md
Labels: blog

#109 Fix categories on network modules
  _modules/cisco_ios.md
  _modules/device_manager.md
  _modules/puppetlabs-panos.md
Labels: bug

#112 Status update for 2020-09-18 status update
  _posts/2020-09-18-status-update.md
Labels: blog

#111 post about docker params change detection
  _posts/2020-09-23-docker-params-change-detection.md
Labels: blog

#114 Bootstrap the weekly status blog!
  bin/blog_tools/Gemfile
  bin/blog_tools/README.md
  bin/blog_tools/blog_template/status-update-template.md.erb
  bin/blog_tools/bootstrap_blog.rb
  bin/blog_tools/lib/common.rb
  bin/blog_tools/lib/community_prs.rb
  bin/blog_tools/lib/modules_released.rb
  bin/blog_tools/lib/octokit_util.rb
Labels: enhancement

#116 2020-09-25 status update
  _posts/2020-09-25-status-update.md
Labels: blog

#118 Update 2020-09-25-status-update.md
  _posts/2020-09-25-status-update.md
Labels: blog

#117 New Blog Site for Interns
  .gitignore
  _config.yml
  _docs/images/mypicture.jpg
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_1.md
  _lifeofinternatpuppet/post_2.md
  _lifeofinternatpuppet/post_3.md
  _lifeofinternatpuppet/post_4.md
Labels: enhancement
