Repository puppetlabs/iac, pull requests merged in 2020-12, with the labels that each got.

#150 (BLOG) Blog Update for Week 14
  _lifeofinternatpuppet/post_14.md
Labels: blog

#151 (blog) Status update 2020-12-02
  _posts/2020-12-04-status-update.md
Labels: blog

#152 Drop i18n tools and modules from support
  _modules/puppetlabs-translate.md
  _tools/puppet-lint-i18n.md
  _tools/puppet_pot_generator.md
  _tools/rubocop-i18n.md
Labels: maintenance

#153 (maint) - Delete i18n header
  _tool_categories/i18n.md
Labels: maintenance

#154 Update all github workflows for modules to new CI location
  _modules/provision.md
  _modules/puppetlabs-accounts.md
  _modules/puppetlabs-acl.md
  _modules/puppetlabs-apache.md
  _modules/puppetlabs-apt.md
  _modules/puppetlabs-chocolatey.md
  _modules/puppetlabs-concat.md
  _modules/puppetlabs-docker.md
  _modules/puppetlabs-dsc.md
  _modules/puppetlabs-dsc_lite.md
  _modules/puppetlabs-exec.md
  _modules/puppetlabs-facter_task.md
  _modules/puppetlabs-firewall.md
  _modules/puppetlabs-haproxy.md
  _modules/puppetlabs-helm.md
  _modules/puppetlabs-ibm_installation_manager.md
  _modules/puppetlabs-iis.md
  _modules/puppetlabs-inifile.md
  _modules/puppetlabs-java.md
  _modules/puppetlabs-java_ks.md
  _modules/puppetlabs-kubernetes.md
  _modules/puppetlabs-motd.md
  _modules/puppetlabs-mysql.md
  _modules/puppetlabs-ntp.md
  _modules/puppetlabs-package.md
  _modules/puppetlabs-postgresql.md
  _modules/puppetlabs-powershell.md
  _modules/puppetlabs-puppet_conf.md
  _modules/puppetlabs-reboot.md
  _modules/puppetlabs-registry.md
  _modules/puppetlabs-rook.md
  _modules/puppetlabs-satellite_pe_tools.md
  _modules/puppetlabs-scheduled_task.md
  _modules/puppetlabs-service.md
  _modules/puppetlabs-sqlserver.md
  _modules/puppetlabs-stdlib.md
  _modules/puppetlabs-tagmail.md
  _modules/puppetlabs-testing.md
  _modules/puppetlabs-tomcat.md
  _modules/puppetlabs-vcsrepo.md
  _modules/puppetlabs-websphere_application_server.md
  _modules/puppetlabs-wsus_client.md
Labels: enhancement

#155 (Blog) Update for Week 15
  _lifeofinternatpuppet/post_15.md
Labels: blog

#156 Status update 2020-12-11
  _posts/2020-12-11-status-update.md
  assets/2020-12-11-status-update/cloud-ci-full-capture.png
  assets/2020-12-11-status-update/pass-fail-honeycomb.png
  bin/blog_tools/blog_template/status-update-template.md.erb
  bin/blog_tools/bootstrap_blog.rb
Labels: blog

#157 Add a quick intro of the team to the main page
  index.md
Labels: enhancement

#161 (blog) Week 16 blog post update
  _lifeofinternatpuppet/post_16.md
Labels: blog

#160 Status update 2020-12-18
  _posts/2020-12-18-status-update.md
  assets/2020-12-18-status-update/christmas.jpg
Labels: blog

#162 (maint) Small update
  _posts/2020-12-18-status-update.md
Labels: blog
