Repository puppetlabs/iac, pull requests merged in 2020-05, with the labels that each got.

#49 Remove whitespace from filename
  _posts/2020-04-17-status-update.md
Labels: maintenance

#45 Fix ia_content email address in footer
  _config.yml
Labels: bug

#52 Fix links to data files
  modules.html
  tools.html
Labels: bug

#53 Add puppet-modulebuilder and puppet-module-gems to our toolset
  _tools/puppet-module-gems.md
  _tools/puppet-modulebuilder.md
Labels: enhancement

#54 (post) - 01/05/2020 IAC Blog Post
  _posts/2020-05-01-status-update.md
Labels: blog

#58 Status update for May 8th
  _posts/2020-03-27-status-update.md
  _posts/2020-05-08-status-update.md
  bin/kerm_to_blog.rb
Labels: blog

#62 IAC blog update for 15.05.2020
  _posts/2020-05-15-status-update.md
Labels: blog

#56 (docs) How we do Pull Requests
  _docs/how-we-do-pull-requests.md
Labels: documentation

#63 Remove resource module from list (unsupported module)
  _modules/puppetlabs-resource.md
Labels: maintenance

#64 2020-05-22 IAC Team Blog Post
  _posts/2020-05-22-status-update.md
  assets/2020-05-22-status-update/vmpooler-abs-migration-tracker.png
Labels: blog

#67 Add demos page
  _docs/demos.md
  _plugins/youtube.rb
Labels: blog, enhancement

#68 2020-05-29: Weekly status update
  .gitignore
  _posts/2020-05-29-status-update.md
Labels: blog
