Repository puppetlabs/iac, pull requests merged in 2020-04, with the labels that each got.

#40 IAC status update for 2020-04-03
  _posts/2020-01-29-infrastructure-automation-content-team.md
  _posts/2020-02-07-status-update.md
  _posts/2020-02-14-status-update.md
  _posts/2020-04-03-status-update.md
Labels: blog

#42 Use new version of jekyll-deploy to avoid "illegal instruction" error
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: bug

#43 Fix typo in 2020-04-03 status update post
  _posts/2020-04-03-status-update.md
Labels: bug

#47 (post) - 16/04/2020 IAC Blog Post
  _posts/2020-04-17-status-update .md
Labels: blog

#50 Copy-edits and additional points
  _posts/2020-04-24-status-update.md
Labels: blog

#51 Link data files and add the IAC repo itself
  _tools/iac-blog.md
  modules.html
  tools.html
Labels: enhancement
