Repository puppetlabs/iac, pull requests merged in 2021-03, with the labels that each got.

#197 (maint) Discard PRs/comment author from github-actions[bot], CLAassistant
  bin/blog_tools/lib/community_prs.rb
Labels: maintenance

#198 Status update for 2021-03-05
  _posts/2021-03-05-status-update.md
Labels: blog

#199 (maint) update module releases
  _posts/2021-03-05-status-update.md
Labels: blog

#201 (maint) Resolve facter task formatting
  _posts/2021-03-05-status-update.md
Labels: maintenance

#202 (blog) Status update for 2021-03-12
  _posts/2021-03-12-status-update.md
  assets/2021-03-12-status-update/actions-report-after.png
  assets/2021-03-12-status-update/actions-report-before.png
Labels: blog

#200 Add link to modules support policy
  modules.html
Labels: documentation

#203 (MAINT) Correct minor formatting issue
  _posts/2021-03-12-status-update.md
Labels: blog

#205 (Blog) Updating Content for Week 17
  _lifeofinternatpuppet/post_17.md
Labels: maintenance

#204 Blog Post 19th March 2021
  _posts/2021-03-19-status-update.md
  assets/2021-03-19-status-update/stp_day.png
Labels: blog

#208 (BLOG) Status Update for 2021-03-26
  _posts/2021-03-26-status-update.md
  assets/2021-03-26-status-update/comm_mgmt_revamp.png
  assets/2021-03-26-status-update/jira_burndown.png
  bin/blog_tools/blog_template/status-update-template.md.erb
  bin/blog_tools/lib/community_prs.rb
  bin/blog_tools/lib/octokit_util.rb
Labels: blog

#209 (IAC-1526) Remove puppetlabs/resource_api from supported modules
  _modules/puppetlabs-resource_api.md
Labels: documentation
