Repository puppetlabs/iac, pull requests merged in 2021-04, with the labels that each got.

#215 (blog) Pending blog posts catchup
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_18.md
  _lifeofinternatpuppet/post_19.md
  _lifeofinternatpuppet/post_20.md
  _lifeofinternatpuppet/post_21.md
  _lifeofinternatpuppet/post_22.md
  _lifeofinternatpuppet/post_23.md
  _lifeofinternatpuppet/post_24.md
  _lifeofinternatpuppet/post_25.md
  _lifeofinternatpuppet/post_26.md
  _lifeofinternatpuppet/post_27.md
  _lifeofinternatpuppet/post_28.md
  _lifeofinternatpuppet/post_29.md
Labels: blog

#218 (Blog) Adding more content in the Week 29 Blog Update
  _lifeofinternatpuppet/post_29.md
Labels: blog

#214 (MAINT) Add specific callout to debug/trace info in issues
  _posts/2021-01-20-reaching-out.md
Labels: maintenance

#219 (bug) (blog) Fixing formatting of Week 29 blog update
  _lifeofinternatpuppet/post_29.md
Labels: blog, bug

#223 (blog), (bug) Adding breaks inside double lists for paragraphs spacing
  _lifeofinternatpuppet/post_29.md
Labels: blog, bug

#222 (blog) (maint) Week 19 Blog Update Minor Fixes
  _lifeofinternatpuppet/post_19.md
Labels: blog, maintenance

#224 (maint) Remove unnecessary title
  _posts/2021-04-02-status-update.md
Labels: blog, maintenance

#226 (blog) Week 30 Update
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_30.md
Labels: blog

#225 (BLOG) Status Update for 2021-04-09
  _posts/2021-04-09-status-update.md
Labels: blog

#227 (blog) (maint) Adding spaces between bullet points and breaks in double lists
  _lifeofinternatpuppet/post_30.md
Labels: blog, maintenance

#228 (maint) Update title to include DevX for template
  bin/blog_tools/blog_template/status-update-template.md.erb
Labels: maintenance

#231 (blog) Week 30 Post Minor Changes Made and Week 31 Blog Update
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_30.md
  _lifeofinternatpuppet/post_31.md
Labels: blog

#232 16-04-21 Blogpost
  _posts/2021-04-16-status-update.md
Labels: blog

#233 (maint) Adding a link to Jira to raise an issue
  _posts/2021-01-20-reaching-out.md
Labels: blog

#235 Blog Update for Week 32
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_32.md
Labels: blog

#229 (DOC) - Role of a reviewer
  _docs/reviewing-pull-requests.md
Labels: documentation

#239 Blog Update for Week 33
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_33.md
Labels: blog
