Repository puppetlabs/iac, pull requests merged in 2021-08, with the labels that each got.

#292 (blog) - Fix grammar, spelling and punctuation mistakes
  _lifeofinternatpuppet/post_10.md
  _lifeofinternatpuppet/post_13.md
  _lifeofinternatpuppet/post_15.md
  _lifeofinternatpuppet/post_17.md
  _lifeofinternatpuppet/post_19.md
  _lifeofinternatpuppet/post_20.md
  _lifeofinternatpuppet/post_21.md
  _lifeofinternatpuppet/post_22.md
  _lifeofinternatpuppet/post_23.md
  _lifeofinternatpuppet/post_24.md
  _lifeofinternatpuppet/post_3.md
  _lifeofinternatpuppet/post_34.md
  _lifeofinternatpuppet/post_37.md
  _lifeofinternatpuppet/post_39.md
  _lifeofinternatpuppet/post_4.md
  _lifeofinternatpuppet/post_41.md
  _lifeofinternatpuppet/post_44.md
  _lifeofinternatpuppet/post_5.md
  _lifeofinternatpuppet/post_7.md
  _lifeofinternatpuppet/post_8.md
Labels: blog

#294 (blog) Formatting corrections in week_3 and week_7 blog posts
  _lifeofinternatpuppet/post_3.md
  _lifeofinternatpuppet/post_7.md
Labels: blog

#295 (blog) updates written for Weeks 45 to 47
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_45.md
  _lifeofinternatpuppet/post_46.md
  _lifeofinternatpuppet/post_47.md
Labels: blog

#296 (blog) Week 45 Blog Update Fix
  _lifeofinternatpuppet/post_45.md
Labels: blog

#297 (MAINT) Update puppet-lint, rspec-puppet namespace
  _tools/puppet-lint.md
  _tools/rspec-puppet.md
Labels: maintenance

#298 (MAINT) Update blog prep and header date to Monday
  .github/workflows/blog_prep.yml
  bin/blog_tools/bootstrap_blog.rb
  bin/blog_tools/lib/common.rb
Labels: maintenance

#300 (MAINT) Run blog prep at 01:00 UTC
  .github/workflows/blog_prep.yml
Labels: maintenance

#306 (GH-305) Remove gem cache steps from deploy and test workflows
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: maintenance

#302 (MAINT) Fix formatting errors in 2021-08-09 post
  _posts/2021-08-09-status-update.md
Labels: blog, maintenance
