Repository puppetlabs/iac, pull requests merged in 2021-06, with the labels that each got.

#255 (blog) Updating blog content
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_10.md
  _lifeofinternatpuppet/post_13.md
  _lifeofinternatpuppet/post_15.md
  _lifeofinternatpuppet/post_16.md
  _lifeofinternatpuppet/post_19.md
  _lifeofinternatpuppet/post_22.md
  _lifeofinternatpuppet/post_23.md
  _lifeofinternatpuppet/post_25.md
  _lifeofinternatpuppet/post_26.md
  _lifeofinternatpuppet/post_4.md
  _lifeofinternatpuppet/post_5.md
  _lifeofinternatpuppet/post_6.md
  _lifeofinternatpuppet/post_7.md
  _lifeofinternatpuppet/post_8.md
  _lifeofinternatpuppet/post_9.md
Labels: blog

#259 (blog), (maint) Adding the correct link to the team status update blog from 20th November 2020
  _posts/2020-11-20-status-update.md
Labels: blog, maintenance

#260 (blog) minor fixes in blog posts 4, 5, 10 & 25
  _lifeofinternatpuppet/post_10.md
  _lifeofinternatpuppet/post_25.md
  _lifeofinternatpuppet/post_4.md
  _lifeofinternatpuppet/post_5.md
Labels: blog

#262 Add automated status update draft preparation workflow
  .github/workflows/blog_prep.yml
  .gitignore
Labels: enhancement

#265 PCT LA Release blog post
  _posts/2021-06-04-pct-early-release.md
Labels: blog

#266 (Blog) Updates to Week 30 Post and Week 37 Blog Update Created
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_30.md
  _lifeofinternatpuppet/post_37.md
Labels: blog

#272 (blog) Week 39 Update
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_39.md
Labels: blog

#270 (blog) update for Week 38
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_38.md
Labels: blog

#273 (MAINT) Fix incorrect link syntax
  _posts/2021-06-11-status-update.md
Labels: blog, bug

#268 (DOC-4989) Multi-node doc edit
  _posts/2021-05-07-running-multinode-modules-gcp.md
Labels: documentation

#277 (maint) fix link
  _posts/2021-05-07-running-multinode-modules-gcp.md
Labels: documentation

#279 (MAINT) Wrap author field in quotes; fix 2021-06-25 post
  _posts/2021-06-25-status-update.md
  bin/blog_tools/blog_template/status-update-template.md.erb
Labels: bug

#275 (blog) Week 40 Update
  _docs/life_of_intern.md
  _lifeofinternatpuppet/post_40.md
Labels: blog

#242 Relocating contributing guidelines to docs site
  _docs/contributing_to_a_module.md
  _docs/pdkunit.png
  _docs/rakespec.png
  _docs/test_run_info.png
Labels: documentation
