Repository puppetlabs/iac, pull requests merged in 2021-02, with the labels that each got.

#184 (GH-90) Converting to use new DSC modules Blog Post
  _posts/2021-01-26-converting-puppetized-dsc-modules.md
Labels: blog

#187 (maint) Correct date
  _posts/2020-05-15-status-update.md
Labels: maintenance

#186 (GH-90) - Add gif to blog post
  assets/2021-01-26-converting-dsc-modules/puppetfile-resolver.gif
Labels: maintenance

#189 Add spacing to fix links for 2021-02-05 status update
  _posts/2021-02-05-status-update.md
Labels: bug

#190 (maint) Correct broken image links for DSC Troubleshooting
  _posts/2021-01-25-troubleshooting-puppetized-dsc-modules.md
Labels: maintenance

#191 Update template to link to Contact blog; add "Other Work" section
  bin/blog_tools/blog_template/status-update-template.md.erb
Labels: maintenance

#192 Add OSPA links; fix some typos
  _posts/2021-01-25-troubleshooting-puppetized-dsc-modules.md
Labels: maintenance

#193 (Blog) 2021-02-12 Status Update
  _posts/2021-02-12-status-update.md
Labels: blog

#194 Remove date from "Reaching out" post
  _posts/2021-01-20-reaching-out.md
Labels: maintenance
